---
extends: default
rules:
  indentation:
    spaces: 2
    indent-sequences: consistent
  quoted-strings:
    quote-type: single
    required: only-when-needed
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on']
