---
apiVersion: v1
kind: Service
metadata:
  labels:
    com.budibase.service: app-service
  name: app-service
spec:
  ports:
  - name: {{ .Values.services.apps.port | quote }}
    port: {{ .Values.services.apps.port }}
    targetPort: {{ .Values.services.apps.port }}
  selector:
    com.budibase.service: app-service
