---
{{- if .Values.services.redis.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    com.budibase.service: redis-data
  name: redis-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.services.redis.storage }}
  {{ if .Values.services.redis.storageClass }}
  storageClassName: {{ .Values.services.redis.storageClass }}
  {{ end }}
{{- end }}
